feat: iamport 웹뷰에서 처리가 불가했던 intent 추가
ik226/react-native-webview-bridge pull request #11
Opened 2019-11-22 07:53 UTC by ik226

### Short description

pg사 웹뷰에서 작동하지 않는 링크가 존재 하여 이에 대한 수정이 필요

### Proposed changes

- 빠져있던 카드사 scheme추가
- 핸들이 안되있던 intent들 처리

2019-11-26 07:37 UTC, saebinna requested changes

2019-11-26 07:37 UTC, saebinna commented on android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java
> +            if (!url.startsWith("http://") && !url.startsWith("https://") && !url.startsWith("javascript:")) {
현재 launchIntent()가 url을 확인하고 실행시키는 로직이 들어가 있어서요 
새로 추가된 로직들도 launchIntent()에 들어가면 좋을 것 같습니다~

2019-11-27 05:55 UTC, ik226 commented on android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java
> +            if (!url.startsWith("http://") && !url.startsWith("https://") && !url.startsWith("javascript:")) {
확인 감사합니다~ 수정할게요~

2019-11-28 05:22 UTC, saebinna approved these changes

2019-11-28 05:40 UTC, merged